### ISSUE TITLE
How to get mapping.json file？

### ISSUE THREAD

**Issue by chendalao** [EricGuo5513/momask-codes#10]
I want to know how to write the corresponding mapping file based on the model?

**Comment by Murrol** [comment]
Hi,

You can create the bone mapping manually by clicking `NEW` under the `Bone Mapping` subsection, or modify the imported Bone Mapping. After you get your own bone mapping, click `Save Bone Mapping File` to save it to the Bone Mapping File Path. More information please refer to the [tutorial](https://www.youtube.com/watch?v=EG-VCMkVpxg) under [👯Visualization](https://github.com/EricGuo5513/momask-codes#dancers-visualization).

Thanks
