### ISSUE TITLE
what is the dataset_opt_path? how to define it? for customized data

### ISSUE THREAD

**Issue by hdjsjyl** [EricGuo5513/momask-codes#12]
Hi author,
    If I want to train the model in my customized data, how do I define dataset_opt_path? Thanks

**Comment by Murrol** [comment]
Hi,

```dataset_opt_path``` is used to load the configure for a pretrained evaluator, which is then used for checkpoint selection. So, to use your own data, you might just disable this feature.

**Comment by hdjsjyl** [comment]
Hi @Murrol , thanks for your reply.

**Comment by AlbertBJ** [comment]
> Hi author, If I want to train the model in my customized data, how do I define dataset_opt_path? Thanks

Hi @hdjsjyl , i also want to train a new model using my own videos, but i have a question is how to convert my own videos to HumanML3D format, thanks a lot
