### ISSUE TITLE
The code loads dataset_opt_path/opt.txt, and text_mot_match/model.finest.tar first, how to generate them for customized data?

### ISSUE THREAD

**Issue by hdjsjyl** [EricGuo5513/momask-codes#13]
Hi Author,
    The code loads the opt.txt and finest.tar first before starting training. How to define them for customized data, would you give me some instructions? Thanks

**Comment by Murrol** [comment]
Hi,

They are used for train-time evaluation. Just disable this feature to train on you own data.

**Comment by hdjsjyl** [comment]
Hi @Murrol , How to evaluate customized trained QVQVAE without evaluator? thx
