### ISSUE TITLE
Loss nan for customized data

### ISSUE THREAD

**Issue by hdjsjyl** [EricGuo5513/momask-codes#14]
Hi Author,
    While I train vaq on my customized data, the loss is nan.  Any suggestion would be appreciated, thanks

![image](https://github.com/EricGuo5513/momask-codes/assets/7590139/c467dfe8-5990-4544-8e9c-84d64ee27a29)

![image](https://github.com/EricGuo5513/momask-codes/assets/7590139/dee61441-09e0-45f4-85d0-72c2b966169f)

**Comment by Murrol** [comment]
You may want to inspect your data to identify any occurrences of NaN or Inf values.

**Comment by hdjsjyl** [comment]
thanks

**Comment by AlbertBJ** [comment]
> thanks

I'm beginer for this field; I want to know how to convert VIBE output to HumanML3D format using my own recorded video. 
thanks
