### ISSUE TITLE
How to evaluate customized trained QVQVAE? since there is no valWrapper

### ISSUE THREAD

**Issue by hdjsjyl** [EricGuo5513/momask-codes#22]
Hi Author,

   I meet the following error while running eval_vq.
  

    AttributeError: 'Namespace' object has no attribute 'dim_movement_enc_hidden'

Thanks

**Comment by Murrol** [comment]
You will need to design and write your own evaluator. If you're unsure, the simplest approach is to comment out all the code related to the missing component and focus only on calculating the reconstruction error.

**Comment by hdjsjyl** [comment]
hi @Murrol , thanks for your reply. If I focus on the reconstruction loss by using l1 loss., I found the best epoch (lowest reconstruction error) is 4th or 5th epoch for batch size of 256 and 512. But I found the generated motion video during training makes sense. Would you point me the sample code in the repo for calculating the reconstruction error or any pseudo code? Really appreciate your help.
