### ISSUE TITLE
ValueError: Imaginary component 

### ISSUE THREAD

**Issue by liloewe** [EricGuo5513/momask-codes#32]
`    raise ValueError('Imaginary component {}'.format(m)) 

ValueError: Imaginary component 5.219298097321144e+25`
Hello, author, I encountered this error when training, have you ever had it?

**Comment by jsun57** [comment]
Same question

**Comment by GuocunWang** [comment]
I am also experiencing this problem. May I ask how it was solved?

```
File "/momask-codes/utils/metrics.py", line 161, in calculate_frechet_distance
    raise ValueError('Imaginary component {}'.format(m))
ValueError: Imaginary component 0.029058187570152688
```
