### ISSUE TITLE
A mean and std computation and use question

### ISSUE THREAD

**Issue by RobinWitch** [EricGuo5513/momask-codes#33]
Hello, what a good work!
While I have a question when I retrain rvqvae, it quite diffuse me a lot.
Why in this place we need to recalculate std?
https://github.com/EricGuo5513/momask-codes/blob/d4d34120ea01e3fda09944c3c030e8befe8c19e2/data/t2m_dataset.py#L41-L68

**Comment by EricGuo5513** [comment]
Hi, here we are calculating group-based std and also amplifying the
importance of certain motion features.

**Comment by RobinWitch** [comment]
In intuitive, I think amplifying the importance of certain motion features we should plus opt.feat_bias instead of dividing? The default value of opt.feat_bias is 5.
