### ISSUE TITLE
 No such file or directory: './checkpoints/t2m/length_estimator/model/finest.tar'

### ISSUE THREAD

**Issue by jzc6915** [EricGuo5513/momask-codes#35]
Hello,during the replication process, I encountered a stumbling block while executing the gen_t2m.py script. Specifically, the script attempts to load a model file named finest.tar from the directory ./checkpoints/t2m/length_estimator/model/, but I was unable to locate this file in the repository or any documentation related to it.

I was wondering if you could offer some guidance on how this file can be obtained or generated. Is it something that should be manually created, or is there a download link available that I might have missed? Your insights on this matter would be greatly appreciated and would greatly facilitate my progress with replicating the project.

Thank you for your time and assistance. I look forward to your advice and continuing to learn from your work.

Warm regards

**Comment by CuiYX03** [comment]
In README.md Get You Ready 2. Models and Dependencies, I think you should run
bash prepare/download_models.sh
to download the folder humanml3dmodels, in this folder there exists a length_estimator.

By the way, I still cannot get the kit/length_estimator so I cannot generate demos by my replicated model on KIT.

**Comment by jzc6915** [comment]
Following the instructions provided in the README.md under the section "Get You Ready 2. Models and Dependencies," I executed the command bash prepare/download_models.sh to download the necessary models, specifically targeting the humanml3dmodels folder for the length_estimator. However, after the download completed, I could only find the Comp_v6_KLD005 and text_mot_match directories within the humanml3d_evaluator folder, and the length_estimator was conspicuously absent.Could you please provide guidance on how I might resolve this issue?

**Comment by CuiYX03** [comment]
can you check your humanml3d_models.zip? In my downloaded folder there exists a folder length_estimator.
![微信图片_20240404161108](https://github.com/EricGuo5513/momask-codes/assets/144914417/5d14bc34-1ee2-48bd-a564-5c68f6092f7d)

**Comment by jzc6915** [comment]
After double-checking, I realized that I had been looking in the wrong folder for the length_estimator. It turns out that it is located in the humanml3d_models directory, not humanml3d_evaluator as I initially thought.

Thank you for your guidance, and apologies for any confusion caused. I appreciate your support, and I'm excited to continue working with your project.

Best regards

**Comment by EricGuo5513** [comment]
> In README.md Get You Ready 2. Models and Dependencies, I think you should run bash prepare/download_models.sh to download the folder humanml3dmodels, in this folder there exists a length_estimator.
> 
> By the way, I still cannot get the kit/length_estimator so I cannot generate demos by my replicated model on KIT.

Hi, thanks for your help on addressing this issue. We only train length_estimator for demonstration only on HumanML3D. For KIT dataset, you may train the length_estimator by your own.
