### ISSUE TITLE
Why there are 2 different mean and variance?

### ISSUE THREAD

**Issue by exitudio** [EricGuo5513/momask-codes#37]
Hi, thank you for opensource your amazaing work.
Why there are 2 different mean and variance from training and testing? Doesn't that cause the discrepancy between training and testing?

1. Training
https://github.com/EricGuo5513/momask-codes/blob/d4d34120ea01e3fda09944c3c030e8befe8c19e2/train_t2m_transformer.py#L134-L135

2. Testing
https://github.com/EricGuo5513/momask-codes/blob/d4d34120ea01e3fda09944c3c030e8befe8c19e2/motion_loaders/dataset_motion_loader.py#L15-L16

**Comment by Murrol** [comment]
Hi, thanks for you interests and careful review of our codes.

We strictly follow the benchmark setting in HumanML3D. Consequently, these two distinct metafiles are numerically identical, sourced directly from the raw dataset's available metadata (Mean.npy and Std.npy) along with the associated weights (opt.feat_bias).

We recognize the importance of using the training mean and std to de-normalize the predicted motion and then re-normalize it with the evaluator's mean and std for a more reliable evaluation process. While they are the same in the basic benchmark setting.

**Comment by exitudio** [comment]
Thank you for your clarification.
