### ISSUE TITLE
retargetting problem

### ISSUE THREAD

**Issue by wang-zm18** [EricGuo5513/momask-codes#39]
Thanks for the detailed tutorials. I have tried [another bvh file](https://drive.google.com/file/d/1hBcc6ceDCQ76z5ImZYSgqnQEmm8kpnjD/view?usp=drive_link)  from the  LAFAN dataset. I got the following visualization result by directly using your provided mapping json file. Are there any solutions or suggestions about this? Thank you in advance!
![image](https://github.com/EricGuo5513/momask-codes/assets/47704679/6c40f26f-31ba-410d-8ea9-fe7fb46a100d)

**Comment by EricGuo5513** [comment]
Our mapping json file is made based on SMPL skeleton. For motions from other datasets, you need to define your own mapping json file. You could refer to video for how to achieve this https://www.youtube.com/watch?v=EG-VCMkVpxg

**Comment by wang-zm18** [comment]
Thank you！ I will have a try!

Chuan Guo ***@***.***> 于2024年4月24日周三 07:09写道：
