### ISSUE TITLE
How to render in like your teaser?

### ISSUE THREAD

**Issue by shunlinlu** [EricGuo5513/momask-codes#4]
Hi, Eric

Thanks for showing such a great work. May I ask how we can visualize like your teaser? In blender, it usually outputs an image sequence with multiple images or one video. How can we combine these images into one animation pic, like your teaser?

Thanks
Shunlin

**Comment by EricGuo5513** [comment]
Hello, we use some kind of silly methods. I separate one motion sequence
into multiple bvh files, where each file only contains one pose. Then I
load all the bvhs in one scene, and render. Please let me know if you try
other ways out.
