### ISSUE TITLE
Gumbel Softmax in Quantizer

### ISSUE THREAD

**Issue by exitudio** [EricGuo5513/momask-codes#41]
Thank you for your amazing work. 
I just want to make sure I understand the code correctly. The Gumbel Sampling is not necessary here, the Argmin version (line 76) will be exactly the same result, correct? 

https://github.com/EricGuo5513/momask-codes/blob/0421a2b8367483ec2a140153037999d9f167a8e6/models/vq/quantizer.py#L76-L78

**Comment by Murrol** [comment]
Hi, we set the sampling temperature here:
https://github.com/EricGuo5513/momask-codes/blob/0421a2b8367483ec2a140153037999d9f167a8e6/models/vq/model.py#L72
So the Gumbel Sampling results would be different from Argmin version. They are from argmin w/ noise.

**Comment by exitudio** [comment]
Thank you for clarification.
