### ISSUE TITLE
"baddbmm__mkl" not implemented for 'Half'

### ISSUE THREAD

**Issue by AndresOM1102** [EricGuo5513/momask-codes#45]
Hello! 
I was trying to run the first line in the demo, but an error occured.
"python gen_t2m.py --gpu_id 1 --ext exp1 --text_prompt "A person is running on a treadmill.". 
It is important to mention, that this is being executed without cuda or GPU, just the CPU. In the attempt of doing so, it loads CLIP correctly however in the step after it fails. The error is the following:

anaconda3/envs/momask/lib/python3.7/site-packages/torch/nn/functional.py", line 4294, in multi_head_attention_forward
    attn_output_weights = torch.bmm(q, k.transpose(1, 2))
RuntimeError: "baddbmm__mkl" not implemented for 'Half'

Of what I have seen, it is an error that can't be solved unless I use cuda or I change some parameters, which I don't know where to change.

**Comment by Murrol** [comment]
Hi,

Pleased refer to this:
https://github.com/EricGuo5513/momask-codes/blob/c7825522ccf259b232aee71418f62724e84e06c3/models/mask_transformer/transformer.py#L184

**Comment by AndresOM1102** [comment]
Hi,

I commented the line, however the same error appears. Do you know what else it might be?

**Comment by AndresOM1102** [comment]
Thanks, it worked!
