### ISSUE TITLE
The Std of the dataset was divided by 5 twice in both the train_dataset and val_dataset, and then it happened to equal the Std of the evaluator?

### ISSUE THREAD

**Issue by Dai-Wenxun** [EricGuo5513/momask-codes#50]
![e096a09368975c39d78a50a8f7c550d](https://github.com/EricGuo5513/momask-codes/assets/58767402/c924256c-2d85-4104-9019-9491bd10b8a7)
![65a1760663a2fc350021cccc2a84e7a](https://github.com/EricGuo5513/momask-codes/assets/58767402/9c206367-3b92-492c-9f73-e245248df8dc)
![88eb201eaad3535920fa70e3f4aec24](https://github.com/EricGuo5513/momask-codes/assets/58767402/622b89f0-97b7-4316-a91e-94e1b8a800d5)
![9f95c9828e7d43591e96a120bf3b2f3](https://github.com/EricGuo5513/momask-codes/assets/58767402/5a920213-c221-4a46-ae10-71c5b19678e0)
![f26e0a8d3aa4ca6372be4a63c72e4e1](https://github.com/EricGuo5513/momask-codes/assets/58767402/1326159f-e578-4b0d-b8d9-7b9899403e32)

**Comment by Dai-Wenxun** [comment]
@EricGuo5513 @Murrol

**Comment by Murrol** [comment]
Yes, it's a bug that remained from the original HuamnML3D project. It performs an in-place operation by mistake.

It's not a serious bug and only affects the weight of the foot contact feature. So, like all other methods on the HumanML3D benchmark, we follow this setting.
https://github.com/EricGuo5513/momask-codes/blob/4e0156ec1f3bd29b8b04e331d840f87d71656a9d/data/t2m_dataset.py#L57

**Comment by Dai-Wenxun** [comment]
Thanks! bro!
