### ISSUE TITLE
the LOST last frame in VQ MotionDataset.

### ISSUE THREAD

**Issue by Dai-Wenxun** [EricGuo5513/momask-codes#51]
In the [getitem](https://github.com/EricGuo5513/momask-codes/blob/main/data/t2m_dataset.py#L79) method of the MotionDataset, I found that the LAST frame of each motion segment cannot be retrieved. 

For example, in the first motion, `self.cumsum[1] = 129`. When `item=129`, there is `idx = 128` since `idx=item-self.cumsum[motion_id=0]-1`, resulting in the motion segment being `[128:128+64] = [128:192]`, while in fact, the length of this motion should be `129+64=193` according to this [line](https://github.com/EricGuo5513/momask-codes/blob/main/data/t2m_dataset.py#L32). This issue occurs with every subsequent motion segment. Should I submit a PR to fix this problem?

**Comment by Dai-Wenxun** [comment]
This issue can be fixed as follows:
```python
self.lengths.append(motion.shape[0] - opt.window_size)
self.lengths.append(motion.shape[0] - opt.window_size + 1)  # Fixed
```

**Comment by Murrol** [comment]
Cool! Thanks for your careful fix. To keep the code consistent, I might not be able to update this.
