### ISSUE TITLE
What GPU is used in training?

### ISSUE THREAD

**Issue by Run542968** [EricGuo5513/momask-codes#53]
Hi, thanks for your excellent works! 
    I want to reproduce this method, could you help to know '**what**' and '**how many**' the **GPUs** are used in your experiments?
    Look forward your reply!

**Comment by EricGuo5513** [comment]
Hi,

We are training on a single old GPU(2080Ti) if I am not wrong.

**Comment by Run542968** [comment]
Thank you for your reply！
