### ISSUE TITLE
Motion sequence length

### ISSUE THREAD

**Issue by erlingling** [EricGuo5513/momask-codes#54]
Thanks for sharing! What I want to know is how the length of the motion sequence generated by this method is determined, unlike the diffusion model?

**Comment by Murrol** [comment]
If I'm not wrong, diffusion models like MDM also pre-set the motion length.

**Comment by erlingling** [comment]
Thanks for your answering, can I follow up and ask if the length of the motion sequence is determined by the user's input prompt, or is the length of the sequence generated by any prompt fixed, i.e. equal to the preset value?

**Comment by Murrol** [comment]
It could be determined by users. 
See https://github.com/GuyTevet/motion-diffusion-model/blob/main/sample/generate.py#L89
https://github.com/GuyTevet/motion-diffusion-model/blob/main/sample/generate.py#L186
