### ISSUE TITLE
why the "renorm operation" is discarded in evaluation process?

### ISSUE THREAD

**Issue by CDLCHOI** [EricGuo5513/momask-codes#56]
In your text-to-motion repository,  renorm is excuted in __getitem__() in _comp_v6_model_dataset.py_。
Why the new evaluation file discard renorm operation?

**Comment by Murrol** [comment]
I guess you're referring to this https://github.com/EricGuo5513/momask-codes/issues/37#issuecomment-2053580110

**Comment by CDLCHOI** [comment]
Sorry, I am not referring to that. 
I found that it's another question, I will ask in a new issue.
