### ISSUE TITLE
The reason for the difference between table 1 and table 2 in the paper.

### ISSUE THREAD

**Issue by HitBadTrap** [EricGuo5513/momask-codes#57]
Hi! I‘m confused about the performance difference between Table 1 and Table 2 in the paper. For instance, in Table 1, the fid and mmdist of momask on HumanML3D are 0.045 and 2.958, respectively. However, in Table 2, the fid and mmdist of momask on HumanML3D are 0.051 and 2.957. Could you tell me the reason for the difference?

**Comment by Murrol** [comment]
Results in Table 2 (in [paper](https://openaccess.thecvf.com/content/CVPR2024/papers/Guo_MoMask_Generative_Masked_Modeling_of_3D_Human_Motions_CVPR_2024_paper.pdf)) are based on the setting of **18** inference steps. In our subsequent sweeping experiment on inference steps, we discovered that **10** steps of inference performed slightly better. Consequently, we report these final results in Table 1.
