### ISSUE TITLE
No such file or directory: './checkpoints/kit/Comp_v6_KLD005/opt.txt'

### ISSUE THREAD

**Issue by liloewe** [EricGuo5513/momask-codes#6]
File "/home/liluwei/master1/project/momask-codes-main/train_vq.py", line 75, in <module>
    wrapper_opt = get_opt(dataset_opt_path, torch.device('cuda'))
  File "/home/liluwei/master1/project/momask-codes-main/utils/get_opt.py", line 37, in get_opt
    with open(opt_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/kit/Comp_v6_KLD005/opt.txt'

Hello, I made this mistake during training, where can I get this file? (./checkpoints/kit/Comp_v6_KLD005/opt.txt)

**Comment by Murrol** [comment]
Hi, it's an evaluator checkpoint we use to select model. Specifically, your missing file could be downloaded by ```gdown --fuzzy https://drive.google.com/file/d/115n1ijntyKDDIZZEuA_aBgffyplNE5az/view?usp=sharing```. More info could be found in [Get You Ready - Models and Dependencies](https://github.com/EricGuo5513/momask-codes?tab=readme-ov-file#round_pushpin-get-you-ready).

**Comment by liloewe** [comment]
Thanks. I'll try

**Comment by Yukuritto** [comment]
> Hi, it's an evaluator checkpoint we use to select model. Specifically, your missing file could be downloaded by
> 
> ```
> gdown --fuzzy https://drive.google.com/file/d/115n1ijntyKDDIZZEuA_aBgffyplNE5az/view?usp=sharing
> ```
> 
> More info could be found in [Get You Ready - Models and Dependencies](https://github.com/EricGuo5513/momask-codes?tab=readme-ov-file#round_pushpin-get-you-ready).

Clicking on the link shows "Access Denied, cannot access content"

**Comment by EricGuo5513** [comment]
Please use the updated link in the GitHub.
