### ISSUE TITLE
Blank aniamtion

### ISSUE THREAD

**Issue by wang-zm18** [EricGuo5513/momask-codes#62]
When I tried to re-train the RVQ.  The result of the saved animation rendering is blank. I have tried multiple params of the camera, however, the problem still remains. Thank you in advance!

**Comment by Murrol** [comment]
It's about the radius of plot_3d. https://github.com/EricGuo5513/momask-codes/commit/4038d850fb390f166033dcce9596aaddaac73016

**Comment by wang-zm18** [comment]
Thank you！
