### ISSUE TITLE
Cannot repreduce the results of the paper in the KIT dataset

### ISSUE THREAD

**Issue by aszxnm** [EricGuo5513/momask-codes#63]
Thank you for your remarkable work. During my experiments, I found that the results after fully training on the KIT dataset are as follows:
FID:0.374，conf.0.020
Diversity:10.659，conf. 0.117
TOP1:0.379,conf.0.007,TOP2.0.583,conf. 0.007,TOP3. 0.709,conf. 0.086
Matching:3.230，conf.0.027
Multimodality:1.308,conf.0.045
Is there anything I should be aware of here?

**Comment by Murrol** [comment]
Hi, thanks for your interests.

You may try to follow the hyper-parameters from the corresponding opt.txt file to config the training scripts.
They should be like these:
```
python train_vq.py --name rvq_replicate --gpu_id 1 --dataset_name kit --batch_size 512 --num_quantizers 6  --max_epoch 20 --quantize_dropout_prob 0.5
```
```
python train_t2m_transformer.py --name mtrans_replicate --gpu_id 1 --dataset_name kit --batch_size 16 --vq_name rvq_replicate --milestones 20_000
python train_res_transformer.py --name rtrans_replicate --gpu_id 2 --dataset_name kit --batch_size 16 --vq_name rvq_replicate --cond_drop_prob 0.2 --share_weight --milestones 20_000
```
