### ISSUE TITLE
What is the advantage to convert SMPL format to 263 dim vector for training?

### ISSUE THREAD

**Issue by Run542968** [EricGuo5513/momask-codes#64]
Hi, thanks for a serious of nice works for the text2motion area. 

I am very confused why I have to convert the SMPL format to 263 dim vectors for training. I read all your article on the subject and found no relevant instructions. 

The vector in dimension 263 contains **root_rot_velocity**, **root_linear_velocity**, **local_joint_postion**, **local_joint_rotation**, **local_joint_velocity**, what is the reason for the `rot_velocity` and the `linear_velociy` are necessary? 

I would appreciate it if you could answer or give me some references!

**Comment by vadeli** [comment]
I think it helps capture the motion’s dynamics better, making transitions between poses smoother. Velocities are key for creating fluid, natural animations, and combining it with foot contacts makes it more realistic in physics-based simulations. By providing the model with more explicit information, it is expected to generate motions that follow the same physical rules.
