### ISSUE TITLE
About length estimator during evaluation

### ISSUE THREAD

**Issue by RohollahHS** [EricGuo5513/momask-codes#65]
Hi, thanks for the great work

1- Are the results in table 1 of paper based on the ground truth lengthes of motions? I did not find length_estimator in eval_t2m_trans_res.py.

2- During evaluation, gumble-softmax is used for random smapling (eval_t2m_trans_res.py), did you use gumble-softmax or Categorical disribution for random sampling during generation (gen_t2m.py)?

Thanks

**Comment by Murrol** [comment]
Hi, thanks for you interests.

1. Yes, it used the ground truth length in evaluation.
2. We use categorical distribution for sampling in gen_t2m.py. There should not be much difference. You can use Gumbel Sampling by using the adding `--gumbel_sample` in your scripts.
