### ISSUE TITLE
Size of training dataset(humanml3d)

### ISSUE THREAD

**Issue by Vinnieassaulter** [EricGuo5513/momask-codes#66]
Hello, I checked the size of the training dataset (num_iters*batch_size) which is about 1847000 entries, which is much larger than the number of entries in Humanml3d. May I ask if you are using some data augmentation method?

**Comment by Murrol** [comment]
I suppose you're referring to the training dataset for vq. So, the dataset for vq training cuts the motion into snippets of length 64. https://github.com/EricGuo5513/momask-codes/blob/4038d850fb390f166033dcce9596aaddaac73016/data/t2m_dataset.py#L15
