### ISSUE TITLE
Why randomly discard a unit_length motion with a one-third probability in __getitem__()?

### ISSUE THREAD

**Issue by JackYu6** [EricGuo5513/momask-codes#69]
Hi, thanks for the great work!
I'm wondering why should we randomly discard a unit_length motion with a one-third probability in __getitem__ function of Text2MotionDatasetEval class and Text2MotionDataset class? Why discard it and why with a one-third probability? 
https://github.com/EricGuo5513/momask-codes/blob/7ac5c2784dee403461558a722f0fdfdf36a3a849/data/t2m_dataset.py#L211-L212
Thank you in advance for your reply.

**Comment by Murrol** [comment]
Hi, thanks for your interest. 

We just follow the benchmark setting from HumanML3D. Probably, it's for some augmentation.
