### ISSUE TITLE
Is the generated npy file with 22 joints for SMPL body model？

### ISSUE THREAD

**Issue by liweiqi11111** [EricGuo5513/momask-codes#70]
If so, how can i turn 22x3 to 24x3 parameters? should i add 2x3 zeros for two hands joints?

**Comment by Murrol** [comment]
Hi, you can refer to https://github.com/GuyTevet/motion-diffusion-model/blob/main/visualize/simplify_loc2rot.py#L124. 

We should set the rotation of hand joints (wrists if I'm no wrong) to zero but not postions.
