### ISSUE TITLE
Inquiries regarding Table 1 and Table 2 in the paper.

### ISSUE THREAD

**Issue by Suzixin7894946** [EricGuo5513/momask-codes#71]
Thank you for your work! I would like to know what the difference is between FID and MM-dist in the Generation column of Table 2 and the FID and MultiModal Dist in Table 1? Why are their values inconsistent?

**Comment by Murrol** [comment]
Hi, please refer to https://github.com/EricGuo5513/momask-codes/issues/57#issuecomment-2184047402
