### ISSUE TITLE
About rendering motions

### ISSUE THREAD

**Issue by RohollahHS** [EricGuo5513/momask-codes#72]
Hi. 

How did you render motions like the following image in the paper? I need it for rendering my motions as an image in my paper.
![image](https://github.com/user-attachments/assets/c8b5b365-fe72-43d2-ba41-6f168f5a2ea2)

Thanks

**Comment by Murrol** [comment]
We used a blender add-on called onion skin.

**Comment by RohollahHS** [comment]
Thanks a lot

**Comment by RohollahHS** [comment]
Did you use "Mesh Onion Skins" ![link](https://github.com/tingjoybits/Mesh_Onion_Skins) add-on?

I could create some markers at different times, but I cannot make their color the same as the object. Could you provide any guidance?
![image](https://github.com/user-attachments/assets/8bb01075-b1f4-4b6d-8404-a911a137f2ff)
