### ISSUE TITLE
Metric changes resulting from changing the training mode

### ISSUE THREAD

**Issue by erlingling** [EricGuo5513/momask-codes#74]
Hello and thank you for your work! I would like to ask if when training the mask transformer, I set the conditional mode to uncond and changed the mask ratio from random to fixed 20%
![ZERHGO ~`E %7%0~K~WQ D9](https://github.com/user-attachments/assets/00242409-9a84-435d-a6c9-67b5a736ae71)
, which results in a large fid (around 17), do you know what this is asking?

**Comment by Murrol** [comment]
The fixed mask ratio would cause inconsistency between training and inference.
