### ISSUE TITLE
Regarding how to train on other datasets

### ISSUE THREAD

**Issue by Suzixin7894946** [EricGuo5513/momask-codes#75]
I would like to ask if you, the author, are familiar with the Babel dataset？ I am interested in training this dataset on your model. Could you please provide me with some suggestions?

**Comment by Murrol** [comment]
Babel is a action-labelled dataset built on AMASS, which is similar to HumanML3D. So it should be easy to convert Babel motions to our 263 motion vectors. You just need to properly slice them according to Babel annotation and convert them using HumanML3D preprocessing scripts.
