### ISSUE TITLE
I found some little mistake in your dataset processing script

### ISSUE THREAD

**Issue by hu394854434** [EricGuo5513/momask-codes#80]
In your script for processing HumanML3D, you mirrored the motion,but did not mirrored the description.For example,"he is waving his left hand",this script may lead to two kind of motion("waving right hand" or  "waving left hand")

**Comment by Murrol** [comment]
Thanks for your interest. Your downloading text annotation should have been mirrored. https://github.com/EricGuo5513/HumanML3D/blob/9176e8fb446b71c7d2a725eb5cf6fec1ae3b3c23/README.md?plain=1#L22
