### ISSUE TITLE
Inquiry Regarding Data in Your Paper

### ISSUE THREAD

**Issue by Suzixin7894946** [EricGuo5513/momask-codes#84]
Dear Authors,
I have some questions about the data presented in your paper:
    1.Regarding the data for MoMask (base) in Table 1, I am curious about how it was derived. My guess is that it might be based on the metrics from the best-performing training round logged in train_m.log. I wonder if this is correct?
    2.For the experimental data on V and q in Table 2, I noticed that there are metrics for HumanML3D but not for KIT-ML. Could you please explain why the KIT-ML-related experiments are missing?
    3.Would it be possible for you to share the code regarding the inference time?

**Comment by Murrol** [comment]
Hi, 

1. if I'm not wrong, momask (base) is our model without the residual transformer.
2. There's no specific reason for not conducting an ablation study on KIT-ML. Just because the space is limited and HumanML3D is much larger.
3. we are not planning to update the inference time evaluation code recently. But this implementation should be quite easy.

**Comment by Suzixin7894946** [comment]
Hello author, I am very interested in your work and have some questions. I hope you can answer them amidst your busy schedule:
1. You mentioned before that Momask (base) does not use res_transformer for generation, which I am aware of. However, I have a question about how the evaluation data for Momask (base) is obtained. I noticed there is a parameter called use_res_model in eval_option. I tried setting it to False, but it caused issues. I speculate that the data is selected from the best round in train_m.log, is that correct?
2. Regarding the ablation study of s and L in Figure 7, could you please tell me how you selected the value of L when scanning the values of s? My understanding is that you used the best value of L for the study, but I am puzzled about how you chose the value of s when looking for the best L. This has caused some confusion in my current experiments.






&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EricGuo5513/momask-codes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月29日(星期二) 上午10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [EricGuo5513/momask-codes] Inquiry Regarding Data in Your Paper (Issue #84)





 
Hi,
  
if I'm not wrong, momask (base) is our model without the residual transformer.
 
There's no specific reason for not conducting an ablation study on KIT-ML. Just because the space is limited and HumanML3D is much larger.
 
we are not planning to update the inference time evaluation code recently. But this implementation should be quite easy.
