### ISSUE TITLE
How can I edit the certain bone length in generation?

### ISSUE THREAD

**Issue by wyyyz1937365497** [EricGuo5513/momask-codes#87]
I used the rig generated by your addon in blender and used auto-rig-pro to remap the animation to my own rig, whose body proportion is not so similar to the generated one. And this made the animation look completely wrong.
How can I edit the certain bone length in generation?  Decreasing the length of arms helped. So how can i make the arms shorter without train a new model?
i`ll be appretiate it if you can slove my problem.

**Comment by Murrol** [comment]
This model is not trained with different born lengths. So, it could be challenging to change it at inference time. You could look for advanced retargeting methods to post-process the generated motion.
