### ISSUE TITLE
Visualization issue

### ISSUE THREAD

**Issue by Suzixin7894946** [EricGuo5513/momask-codes#88]
When I use the sentence "A person walks forwards, sits" to generate a sequence, there is a noticeable error in the foot posture. Have you encountered this issue in visualization before? Could you offer some suggestions to resolve it?
![0061](https://github.com/user-attachments/assets/85455a79-b393-4e91-b844-1dfdef5b0f35)

**Comment by Murrol** [comment]
Fixing the ankle rotation to default before exporting .bvh might help
