### ISSUE TITLE
There is no Comp_v6_KLD005/opt.txt for training vq

### ISSUE THREAD

**Issue by MD-Student** [EricGuo5513/momask-codes#92]
@Murrol Thanks for your great work. I want to train a new vqvae without down sampling on HumanML3d dataset. However when I run `train_vq` script, it threw an error saying no such file `Comp_v6_KLD005/opt.txt`.

Where could I download this file? Or how can I train the vq without the evaluation stage?

**Comment by Murrol** [comment]
Please see #6

**Comment by Solo4working** [comment]
> Please see #6

Hi, @Murrol . 
I downloaded the file (kit_models.zip) from Google Drive (https://drive.google.com/drive/folders/1sHajltuE2xgHh91H9pFpMAYAkHaX9o57), but I don't see the Comp_v6_KLD005 folder, just three folders: rvq, t2m, tres. Am I missing something?

**Comment by Murrol** [comment]
> > Please see #6
> 
> Hi, @Murrol . I downloaded the file (kit_models.zip) from Google Drive (https://drive.google.com/drive/folders/1sHajltuE2xgHh91H9pFpMAYAkHaX9o57), but I don't see the Comp_v6_KLD005 folder, just three folders: rvq, t2m, tres. Am I missing something?

It's in kit_evaluator.zip

**Comment by Solo4working** [comment]
> > > Please see #6
> > 
> > 
> > Hi, @Murrol . I downloaded the file (kit_models.zip) from Google Drive (https://drive.google.com/drive/folders/1sHajltuE2xgHh91H9pFpMAYAkHaX9o57), but I don't see the Comp_v6_KLD005 folder, just three folders: rvq, t2m, tres. Am I missing something?
> 
> It's in kit_evaluator.zip

Thx! I got it!
